/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductListImport } from './routes/product/list'
import { Route as ProductAddImport } from './routes/product/add'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductListRoute = ProductListImport.update({
  id: '/product/list',
  path: '/product/list',
  getParentRoute: () => rootRoute,
} as any)

const ProductAddRoute = ProductAddImport.update({
  id: '/product/add',
  path: '/product/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/product/add': {
      id: '/product/add'
      path: '/product/add'
      fullPath: '/product/add'
      preLoaderRoute: typeof ProductAddImport
      parentRoute: typeof rootRoute
    }
    '/product/list': {
      id: '/product/list'
      path: '/product/list'
      fullPath: '/product/list'
      preLoaderRoute: typeof ProductListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/add': typeof ProductAddRoute
  '/product/list': typeof ProductListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/add': typeof ProductAddRoute
  '/product/list': typeof ProductListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/product/add': typeof ProductAddRoute
  '/product/list': typeof ProductListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/add' | '/product/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/add' | '/product/list'
  id: '__root__' | '/' | '/product/add' | '/product/list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductAddRoute: typeof ProductAddRoute
  ProductListRoute: typeof ProductListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductAddRoute: ProductAddRoute,
  ProductListRoute: ProductListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product/add",
        "/product/list"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/product/add": {
      "filePath": "product/add.tsx"
    },
    "/product/list": {
      "filePath": "product/list.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
